//making the table importername exportername importercode exportercode year value


global dir = "D:/00_work/04_Data"


use "$dir/1.dta", replace
gen importername ="im"
gen exportername ="ex"

//country name
replace importername ="UNITED STATES" if cty1 =="111"
replace importername ="UNITED KINGDOM" if cty1 =="112"
replace importername ="FRANCE" if cty1 =="132"
replace importername ="GERMANY" if cty1 =="134"
replace importername ="CANADA" if cty1 =="156"
replace importername ="JAPAN" if cty1 =="158"
replace importername ="SOUTH AFRICA" if cty1 =="199"
replace importername ="BRAZIL" if cty1 =="223"
replace importername ="VENEZUELA, REP. BOL." if cty1 =="299"
replace importername ="IRAN, I.R. OF" if cty1 =="429"
replace importername ="ISRAEL" if cty1 =="436"
replace importername ="INDIA" if cty1 =="534"
replace importername ="SOUTH KOREA" if cty1 =="542"
replace importername ="PAKISTAN" if cty1 =="564"
replace importername ="RUSSIA" if cty1 =="922"
replace importername ="CHINA,P.R.: MAINLAND" if cty1 =="924"
replace importername ="NORTH KOREA" if cty1 =="954"

replace exportername ="UNITED STATES" if cty2 =="111"
replace exportername ="UNITED KINGDOM" if cty2 =="112"
replace exportername ="FRANCE" if cty2 =="132"
replace exportername ="GERMANY" if cty2 =="134"
replace exportername ="ITALY" if cty2 =="136"
replace exportername ="CANADA" if cty2 =="156"
replace exportername ="JAPAN" if cty2 =="158"
replace exportername ="FINLAND" if cty2 =="172"
replace exportername ="GREECE" if cty2 =="174"
replace exportername ="PORTUGAL" if cty2 =="182"
replace exportername ="SPAIN" if cty2 =="184"
replace exportername ="TURKEY" if cty2 =="186"
replace exportername ="AUSTRALIA" if cty2 =="193"
replace exportername ="SOUTH AFRICA" if cty2 =="199"
replace exportername ="ARGENTINA" if cty2 =="213"
replace exportername ="BRAZIL" if cty2 =="223"
replace exportername ="CHILE" if cty2 =="228"
replace exportername ="MEXICO" if cty2 =="273"
replace exportername ="PERU" if cty2 =="293"
replace exportername ="IRAN, I.R. OF" if cty2 =="429"
replace exportername ="IRAQ" if cty2 =="433"
replace exportername ="ISRAEL" if cty2 =="436"
replace exportername ="LEBANON" if cty2 =="446"
replace exportername ="SAUDI ARABIA" if cty2 =="456"
replace exportername ="UNITED ARAB EMIRATES" if cty2 =="466"
replace exportername ="EGYPT" if cty2 =="469"
replace exportername ="AFGHANISTAN, I.S. OF" if cty2 =="512"
replace exportername ="SRI LANKA" if cty2 =="524"
replace exportername ="INDIA" if cty2 =="534"
replace exportername ="INDONESIA" if cty2 =="536"
replace exportername ="SOUTH KOREA" if cty2 =="542"
replace exportername ="PAKISTAN" if cty2 =="564"
replace exportername ="PHILIPPINES" if cty2 =="566"
replace exportername ="THAILAND" if cty2 =="578"
replace exportername ="CONGO, DEM. REP. OF" if cty2 =="636"
replace exportername ="GHANA" if cty2 =="652"
replace exportername ="KENYA" if cty2 =="664"
replace exportername ="NIGERIA" if cty2 =="694"
replace exportername ="ZIMBABWE" if cty2 =="698"
replace exportername ="SENEGAL" if cty2 =="722"
replace exportername ="TANZANIA" if cty2 =="738"
replace exportername ="AZERBAIJAN" if cty2 =="912"
replace exportername ="RUSSIA" if cty2 =="922"
replace exportername ="CHINA,P.R.: MAINLAND" if cty2 =="924"
replace exportername ="HUNGARY" if cty2 =="944"
replace exportername ="POLAND" if cty2 =="964"

//list the combinations of country

save "$dir/table0.dta", replace

